export const THEMES = [
  'transit', 'ember', 'forest', 'light', 'monochrome',
  'ocean', 'sunset', 'aurora', 'noir', 'sunrise',
  'retro', 'wine', 'tron', 'paper', 'midnight',
  'candy', 'sakura', 'copper', 'nord', 'autumn',
  'mint', 'ruby', 'lavender', 'sand', 'plasma',
  'mono-light',
  'magma', 'frost', 'cobalt', 'jade', 'terra',
  'neon-night', 'sepia', 'arctic', 'twilight',
  'radioactive', 'champagne', 'slate', 'honey',
  'moonlight', 'peach', 'ink', 'crimson', 'sage',
  'storm',
] as const;

export type Theme = (typeof THEMES)[number];

export const THEME_LABELS: Record<string, string> = {
  transit: 'Transit',
  ember: 'Ember',
  forest: 'Forest',
  light: 'Light',
  monochrome: 'Mono',
  ocean: 'Ocean',
  sunset: 'Sunset',
  aurora: 'Aurora',
  noir: 'Noir',
  sunrise: 'Sunrise',
  retro: 'Retro',
  wine: 'Wine',
  tron: 'Tron',
  paper: 'Paper',
  midnight: 'Midnight',
  candy: 'Candy',
  sakura: 'Sakura',
  copper: 'Copper',
  nord: 'Nord',
  autumn: 'Autumn',
  mint: 'Mint',
  ruby: 'Ruby',
  lavender: 'Lavender',
  sand: 'Sand',
  plasma: 'Plasma',
  'mono-light': 'Mono Light',
  magma: 'Magma',
  frost: 'Frost',
  cobalt: 'Cobalt',
  jade: 'Jade',
  terra: 'Terra',
  'neon-night': 'Neon Night',
  sepia: 'Sepia',
  arctic: 'Arctic',
  twilight: 'Twilight',
  radioactive: 'Radioactive',
  champagne: 'Champagne',
  slate: 'Slate',
  honey: 'Honey',
  moonlight: 'Moonlight',
  peach: 'Peach',
  ink: 'Ink',
  crimson: 'Crimson',
  sage: 'Sage',
  storm: 'Storm',
};

export const THEME_DESCRIPTIONS: Record<string, string> = {
  transit: 'Deep navy/blue transit-map look',
  ember: 'Warm amber/copper on dark',
  forest: 'Cool teal/emerald tones',
  light: 'Clean light-background theme',
  monochrome: 'Monochrome greyscale',
  ocean: 'Deep blue-green oceanic tones',
  sunset: 'Warm dusk gradients — purple, orange, gold',
  aurora: 'Aurora Borealis — cool cyan to green',
  noir: 'High-contrast black & white',
  sunrise: 'Bright coral-to-cream on dark',
  retro: 'CRT-terminal green on near-black',
  wine: 'Deep burgundy and muted gold',
  tron: 'Electric cyan-and-magenta cyberpunk',
  paper: 'Warm cream background with slate',
  midnight: 'Ultra-dark indigo with cool silver',
  candy: 'Bright pastels on dark',
  sakura: 'Cherry blossom pinks and soft greens',
  copper: 'Warm copper and patina',
  nord: 'Nordic frosty blues and muted snow',
  autumn: 'Fallen leaves — oranges, reds, ochre',
  mint: 'Fresh mint and cool grey',
  ruby: 'Rich red gemstone with warm gold',
  lavender: 'Soft purples and muted mauve',
  sand: 'Warm desert tones — tan, terracotta, sage',
  plasma: 'Hot plasma — incandescent yellows through reds',
  'mono-light': 'Clean light monochrome',
  magma: 'Molten rock — deep reds through bright orange',
  frost: 'Icy blues and silver on near-black',
  cobalt: 'Rich cobalt blue with warm accents',
  jade: 'Lush green gemstone with gold highlights',
  terra: 'Earthy browns, sienna, muted sage',
  'neon-night': 'Synthwave — deep purple with hot pink and cyan',
  sepia: 'Warm vintage photo tones',
  arctic: 'Bright, clean — white, pale blue, cool grey',
  twilight: 'Evening sky — deep blue-purple transition',
  radioactive: 'High-contrast lime green on pitch black',
  champagne: 'Elegant golds and creams on dark brown',
  slate: 'Cool blue-grey — modern, understated',
  honey: 'Warm golden amber — cheerful yet legible',
  moonlight: 'Cool silver-blue on dark — serene',
  peach: 'Soft peach and coral on warm light background',
  ink: 'Blueprint-style — white grid on deep blue',
  crimson: 'Bold red and carmine — intense and dramatic',
  sage: 'Muted green-grey — calm, organic, understated',
  storm: 'Dark stormy grey with electric blue accents',
};

export const DEFAULT_THEME: string = 'transit';
